.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 "Osamu Aoki" <osamu@debian.org>,
.TH HELLO 1 "2015-01-12"
.SH NAME
hello \- example executable program
.SH SYNOPSIS
.B hello
.SH DESCRIPTION
This is an example executable program to print a short text message to check
how the Debian packaging went.
.SH OPTIONS
None available.
.SH SEE ALSO
.BR debmake (1)
and documentation in the
.BR debmake-doc
package.
